import htmlmin from 'html-minifier-terser';

const isProduction = process.env.ELEVENTY_ENV === 'production';

export const htmlConfig = eleventyConfig => {
  eleventyConfig.addTransform('html-minify', (content, path) => {
    if (path && path.endsWith('.html') && isProduction) {
      return htmlmin.minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeComments: true,
        // Preserve mermaid diagram blocks - they need newlines to parse correctly
        // The regex matches both div and pre tags with mermaid class
        ignoreCustomFragments: [
          /<(?:div|pre)[^>]*class="mermaid"[^>]*>[\s\S]*?<\/(?:div|pre)>/g
        ]
      });
    }

    return content;
  });
};
